/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2019-09-02 07:59:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cusdevplanManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t//搜索\r\n");
      out.write("\tfunction searchSaleChance(){\r\n");
      out.write("\t\t$(\"#dg\").datagrid(\"load\",{\r\n");
      out.write("\t\t\t\"customerName\":$(\"#s_customerName\").val(),\r\n");
      out.write("\t\t\t\"overView\":$(\"#s_overView\").val(),\r\n");
      out.write("\t\t\t\"devResult\":$(\"#s_devResult\").combobox(\"getValue\")\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//处理分配状态显示的值\r\n");
      out.write("\tfunction formatState(value,row){\r\n");
      out.write("\t\tif(row.state == 1){\r\n");
      out.write("\t\t\treturn \"已分配\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn \"未分配\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//处理开发状态显示的值\r\n");
      out.write("\tfunction formatDevResult(value,row){\r\n");
      out.write("\t\tif(row.devResult==0){\r\n");
      out.write("\t\t\treturn \"未开发\";\r\n");
      out.write("\t\t}else if(row.devResult==1){\r\n");
      out.write("\t\t\treturn \"开发中\";\r\n");
      out.write("\t\t}else if(row.devResult==2){\r\n");
      out.write("\t\t\treturn \"开发成功\";\r\n");
      out.write("\t\t}else if(row.devResult==3){\r\n");
      out.write("\t\t\treturn \"开发失败\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//调用父窗体的openTab方法，打开一个新的窗口\r\n");
      out.write("\tfunction openCusDevPlanTab(id){\r\n");
      out.write("\t\twindow.parent.openTab('客户开发计划项管理','cusdevplanitemManage.jsp?saleChanceId='+id,'icon-khkfjh');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openCusDevPlanTab2(id){\r\n");
      out.write("\t\twindow.parent.openTab('查看客户开发计划','cusdevplanitemManage.jsp?saleChanceId='+id+'&detailed=show','icon-khkfjh');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//处理需要显示的按钮\r\n");
      out.write("\tfunction formatAction(value,row){\r\n");
      out.write("\t\tif(row.devResult == 0 || row.devResult==1){\r\n");
      out.write("\t\t\treturn \"<a href='javascript:openCusDevPlanTab(\"+row.id+\")'>开发</a>\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn \"<a href='javascript:openCusDevPlanTab2(\"+row.id+\")'>查看详情</a>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<table id=\"dg\" title=\"客户开发机会管理\" class=\"easyui-datagrid\" fitColumns=\"true\" pagination=\"true\" rownumbers=\"true\"\r\n");
      out.write("\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/saleChance/list.do?state=1\" fit=\"true\" toolbar=\"#tb\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"cb\" checkbox=\"true\" align=\"center\"></th>\r\n");
      out.write("\t\t\t\t<th field=\"id\" width=\"20px\" align=\"center\">编号</th>\r\n");
      out.write("\t\t\t\t<th field=\"chanceSource\" width=\"50px\" align=\"center\" hidden=\"true\">机会来源</th>\r\n");
      out.write("\t\t\t\t<th field=\"customerName\" width=\"50px\" align=\"center\">客户名称</th>\r\n");
      out.write("\t\t\t\t<th field=\"cgjl\" width=\"50px\" align=\"center\" hidden=\"true\">成功几率</th>\r\n");
      out.write("\t\t\t\t<th field=\"overView\" width=\"50px\" align=\"center\">概要</th>\r\n");
      out.write("\t\t\t\t<th field=\"linkMan\" width=\"50px\" align=\"center\">联系人</th>\r\n");
      out.write("\t\t\t\t<th field=\"linkPhone\" width=\"50px\" align=\"center\" hidden=\"true\">联系电话</th>\r\n");
      out.write("\t\t\t\t<th field=\"description\" width=\"50px\" align=\"center\" hidden=\"true\">机会描述</th>\r\n");
      out.write("\t\t\t\t<th field=\"createMan\" width=\"50px\" align=\"center\">创建人</th>\r\n");
      out.write("\t\t\t\t<th field=\"createTime\" width=\"50px\" align=\"center\">创建时间</th>\r\n");
      out.write("\t\t\t\t<th field=\"assignMan\" width=\"50px\" align=\"center\">指派人</th>\r\n");
      out.write("\t\t\t\t<th field=\"assignTime\" width=\"50px\" align=\"center\">指派时间</th>\r\n");
      out.write("\t\t\t\t<th field=\"state\" width=\"50px\" align=\"center\" hidden=\"true\" formatter=\"formatState\">分配状态</th>\r\n");
      out.write("\t\t\t\t<th field=\"devResult\" width=\"50px\" align=\"center\" formatter=\"formatDevResult\">客户开发状态</th>\r\n");
      out.write("\t\t\t\t<th field=\"a\" width=\"50px\" align=\"center\" formatter=\"formatAction\">操作</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead> \r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"tb\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t&nbsp;客户名称：<input type=\"text\" id=\"s_customerName\" size=\"20\" onkeydown=\"if(event.keyCode==13) searchSaleChance()\"/>\r\n");
      out.write("\t\t\t&nbsp;概要：<input type=\"text\" id=\"s_overView\" size=\"20\" onkeydown=\"if(event.keyCode==13) searchSaleChance()\"/>\r\n");
      out.write("\t\t\t&nbsp;开发状态：<select class=\"easyui-combobox\" id=\"s_devResult\" editable=\"false\" panelHeight=\"auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">未开发</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">开发中</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">开发成功</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">开发失败</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t<a href=\"javascript:searchSaleChance()\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">搜索</a>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
