/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2019-09-02 07:59:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customerManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar url;\t//全局变量：每个函数都会用，链接地址\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchCustomer(){\r\n");
      out.write("\t\t$(\"#dg\").datagrid(\"load\",{\r\n");
      out.write("\t\t\t\"khno\":$(\"#s_khno\").val(),\t\r\n");
      out.write("\t\t\t\"name\":$(\"#s_name\").val()\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//打开用户对话框(添加)\r\n");
      out.write("\tfunction openCustomerAddDialog(){\r\n");
      out.write("\t\t//resetValue();\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"添加客户信息\");\r\n");
      out.write("\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/customer/save.do\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//打开用户对话框(修改)\r\n");
      out.write("\tfunction openCustomerModifyDialog(){\r\n");
      out.write("\t\t//获取用户选中的行(可以选中多行，但只能修改一行)\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif(selectRows.length != 1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要编辑的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = selectRows[0];\t\t//当前记录的所有属性值\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"修改数据字典信息\");\r\n");
      out.write("\t\t//给对话框里面的表单赋值\r\n");
      out.write("\t\t$(\"#fm\").form(\"load\",row);\r\n");
      out.write("\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/customer/save.do?id=\"+row.id;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//保存\r\n");
      out.write("\tfunction saveCustomer(){\r\n");
      out.write("\t\t$(\"#fm\").form(\"submit\",{\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tonSubmit:function(){\r\n");
      out.write("\t\t\t\t//判断下拉框是否选中\r\n");
      out.write("\t\t\t\tif($(\"#area\").combobox(\"getValue\") == \"\"){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"请选择客户地区\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#cusManager\").combobox(\"getValue\") == \"\"){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"请选择客户经理\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#level\").combobox(\"getValue\") == \"\"){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"请选择客户等级\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#myd\").combobox(\"getValue\") == \"\"){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"请选择客户满意度\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#xyd\").combobox(\"getValue\") == \"\"){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"请选择客户信用度\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//所有数据填充完毕，进行最后一次验证表单\r\n");
      out.write("\t\t\t\treturn $(this).form(\"validate\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"保存成功！\");\r\n");
      out.write("\t\t\t\t\t//重置属性值\r\n");
      out.write("\t\t\t\t\tresetValue();\r\n");
      out.write("\t\t\t\t\t//关闭对话框\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t//刷新表格数据\r\n");
      out.write("\t\t\t\t\t$(\"#dg\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"保存失败！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\tfunction openCustomerLinkMan(){\r\n");
      out.write("\t\t//获取用户选中的行(可以选中多行,但只能查看一行)\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif(selectRows.length != 1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要管理的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = selectRows[0];\r\n");
      out.write("\t\twindow.parent.openTab('联系人管理','linkManManage.jsp?cusId='+row.id,'icon-lxr');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openCustomerContact(){\r\n");
      out.write("\t\t//获取用户选中的行(可以选中多行,但只能查看一行)\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif(selectRows.length != 1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要管理的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = selectRows[0];\r\n");
      out.write("\t\twindow.parent.openTab('交往记录管理','contactManage.jsp?cusId='+row.id,'icon-jwjl');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openCustomerOrder(){\r\n");
      out.write("\t\t//获取用户选中的行(可以选中多行,但只能查看一行)\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif(selectRows.length != 1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要查看的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = selectRows[0];\r\n");
      out.write("\t\twindow.parent.openTab('历史订单查看','orderManage.jsp?cusId='+row.id,'icon-lsdd');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//删除\r\n");
      out.write("\tfunction deleteCustomer(){\r\n");
      out.write("\t\t//获取用户选中的行(可以选中多行)\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif(selectRows.length == 0){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择要删除的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//存储用户所选中行的id\r\n");
      out.write("\t\tvar strIds = [];\r\n");
      out.write("\t\tfor(var i=0;i < selectRows.length;i++){\r\n");
      out.write("\t\t\t//把选中记录的id存到strIds数组里面\r\n");
      out.write("\t\t\tstrIds.push(selectRows[i].id)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//将数组变成字符串，按指定的符号隔开 [11,12]   \t\"11,12\"\r\n");
      out.write("\t\tvar ids = strIds.join(\",\");\r\n");
      out.write("\t\t$.messager.confirm(\"系统提示\",\"您却定要删除这<font color='red' size='3'>\"+selectRows.length+\"</font>条记录吗？\",function(r){\r\n");
      out.write("\t\t\tif(r){\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/customer/delete.do\",{ids:ids},function (result){\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"系统提示\",\"数据删除成功！\");\r\n");
      out.write("\t\t\t\t\t\t//刷新表格数据\r\n");
      out.write("\t\t\t\t\t\t$(\"#dg\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"系统提示\",\"数据删除失败！\");\r\n");
      out.write("\t\t\t\t\t}         \r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//关闭\r\n");
      out.write("\tfunction closeCustomerDialog(){\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\tresetValue();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//重置\r\n");
      out.write("\tfunction resetValue(){\r\n");
      out.write("\t\t//$(\"#dataDicName\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"name\").val(\"\");\r\n");
      out.write("\t\t$(\"#area\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#cusManager\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#level\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#myd\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#xyd\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#postCode\").val(\"\");\r\n");
      out.write("\t\t$(\"#phone\").val(\"\");\r\n");
      out.write("\t\t$(\"#fax\").val(\"\");\r\n");
      out.write("\t\t$(\"#webSite\").val(\"\");\r\n");
      out.write("\t\t$(\"#yyzzzch\").val(\"\");\r\n");
      out.write("\t\t$(\"#fr\").val(\"\");\r\n");
      out.write("\t\t$(\"#zczj\").val(\"\");\r\n");
      out.write("\t\t$(\"#nyye\").val(\"\");\r\n");
      out.write("\t\t$(\"#khyh\").val(\"\");\r\n");
      out.write("\t\t$(\"#khzh\").val(\"\");\r\n");
      out.write("\t\t$(\"#dsdjh\").val(\"\");\r\n");
      out.write("\t\t$(\"#gsdjh\").val(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"dg\" title=\"客户信息管理\" class=\"easyui-datagrid\" pagination=\"true\" rownumbers=\"true\"\r\n");
      out.write("\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/customer/list.do\" fit=\"true\" toolbar=\"#tb\">\r\n");
      out.write("\t\t<thead data-options=\"frozen:true\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th field=\"cb\" checkbox=\"true\" align=\"center\"></th>\r\n");
      out.write("\t\t\t \t\t<th field=\"id\" width=\"50\" align=\"center\" hidden=\"true\">编号</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"khno\" width=\"150\" align=\"center\">客户编号</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"name\" width=\"200\" align=\"center\">客户名称</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"cusManager\" width=\"100\" align=\"center\">客户经理</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"level\" width=\"100\" align=\"center\">客户等级</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"phone\" width=\"100\" align=\"center\">联系电话</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th field=\"area\" width=\"80\" align=\"center\">客户地区</th>\t\r\n");
      out.write("\t\t\t \t\t<th field=\"myd\" width=\"80\" align=\"center\">客户满意度</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"xyd\" width=\"80\" align=\"center\">客户信用度</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"address\" width=\"200\" align=\"center\" >客户地址</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"postCode\" width=\"100\" align=\"center\" >邮政编码</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"fax\" width=\"100\" align=\"center\" >传真</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"webSite\" width=\"100\" align=\"center\" >网址</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"yyzzzch\" width=\"100\" align=\"center\" >营业执照注册号</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"fr\" width=\"100\" align=\"center\" >法人</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"zczj\" width=\"100\" align=\"center\" >注册资金(万元)</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"nyye\" width=\"100\" align=\"center\" >年营业额(万元)</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"khyh\" width=\"100\" align=\"center\" >开户银行</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"khzh\" width=\"100\" align=\"center\" >开户帐号</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"dsdjh\" width=\"100\" align=\"center\" >地税登记号</th>\r\n");
      out.write("\t\t\t \t\t<th field=\"gsdjh\" width=\"100\" align=\"center\" >国税登记号</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"tb\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a href=\"javascript:openCustomerAddDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">添加</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:openCustomerModifyDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">修改</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:deleteCustomer()\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">删除</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:openCustomerLinkMan()\" class=\"easyui-linkbutton\" iconCls=\"icon-lxr\" plain=\"true\">联系人管理</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:openCustomerContact()\" class=\"easyui-linkbutton\" iconCls=\"icon-jwjl\" plain=\"true\">交往记录管理</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:openCustomerOrder()\" class=\"easyui-linkbutton\" iconCls=\"icon-lsdd\" plain=\"true\">客户历史订单查看</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t&nbsp;客户编号：<input type=\"text\" id=\"s_khno\" size=\"20\" onkeydown=\"if(event.keyCode==13) searchCustomer()\"/>\r\n");
      out.write("\t\t\t&nbsp;客户名称：<input type=\"text\" id=\"s_name\" size=\"20\" onkeydown=\"if(event.keyCode==13) searchCustomer()\"/>\r\n");
      out.write("\t\t\t<a href=\"javascript:searchCustomer()\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">搜索</a>\r\n");
      out.write("\t\t</div>               \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:700px;height:500px;padding:10px 20px\" closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"8px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>客户名称：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"name\" name=\"name\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>地区：</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" id=\"area\" name=\"area\" style=\"width:145px\" editable=\"false\" panelHeight=\"auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择地区...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"湖南\">湖南</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"上海\">上海</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"厦门\">厦门</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"西藏\">西藏</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;<font color=\"red\">*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>客户经理：</td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"easyui-combobox\" id=\"cusManager\" name=\"cusManager\" panelHeight=\"auto\" editable=\"false\" valueField=\"trueName\" textField=\"trueName\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/customerManagerComboList.do\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>客户等级：</td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"easyui-combobox\" id=\"level\" name=\"level\" panelHeight=\"auto\" editable=\"false\" valueField=\"dataDicValue\" textField=\"dataDicValue\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dataDic/dataDicComboList.do\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>客户满意度：</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" id=\"myd\" name=\"myd\" style=\"width:145px\" editable=\"false\" panelHeight=\"auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆\">☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆\">☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆☆\">☆☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆☆☆\">☆☆☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆☆☆☆\">☆☆☆☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;<font color=\"red\">*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>客户信用度：</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" id=\"xyd\" name=\"xyd\" style=\"width:145px\" editable=\"false\" panelHeight=\"auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆\">☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆\">☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆☆\">☆☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆☆☆\">☆☆☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"☆☆☆☆☆\">☆☆☆☆☆</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;<font color=\"red\">*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>邮政编码：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"postCode\" name=\"postCode\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>联系电话：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"phone\" name=\"phone\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>传真：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"fax\" name=\"fax\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>网址：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"webSite\" name=\"webSite\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>客户地址：</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><input type=\"text\" id=\"address\" name=\"address\" class=\"easyui-validatebox\" style=\"width:433px\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>营业执照注册号：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"yyzzzch\" name=\"yyzzzch\" class=\"easyui-validatebox\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>法人：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"fr\" name=\"fr\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>注册资金(万元)：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"zczj\" name=\"zczj\" class=\"easyui-validatebox\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>年营业额(万元)：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"nyye\" name=\"nyye\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>开户银行：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"khyh\" name=\"khyh\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>开户账号：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"khzh\" name=\"khzh\" class=\"easyui-validatebox\" required=\"true\"/>&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>地税登记号：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"dsdjh\" name=\"dsdjh\" class=\"easyui-validatebox\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>国税登记号：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"gsdjh\" name=\"gsdjh\" class=\"easyui-validatebox\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>                                                                                                                    \r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:saveCustomer()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">保存</a>\r\n");
      out.write("\t\t<a href=\"javascript:closeCustomerDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">关闭</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
