/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2019-09-02 07:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customerServiceAssign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar url;\t//全局变量：每个函数都会用，链接地址\r\n");
      out.write("\t\r\n");
      out.write("\t//打开用户对话框(修改)\r\n");
      out.write("\tfunction openCustomerServiceAssignDialog(){\r\n");
      out.write("\t\t//获取用户选中的行(可以选中多行，但只能修改一行)\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif(selectRows.length != 1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要分配的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = selectRows[0];\t\t//当前记录的所有属性值\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"分配客户服务\");\r\n");
      out.write("\t\t//给对话框里面的表单赋值\r\n");
      out.write("\t\t$(\"#fm\").form(\"load\",row);\r\n");
      out.write("\t\t$(\"#state\").val(\"已分配\");\r\n");
      out.write("\t\t$(\"#assignTime\").val(getCurrentDate());\r\n");
      out.write("\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/customerService/save.do?id=\"+row.id;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//保存\r\n");
      out.write("\tfunction saveCustomerService(){\r\n");
      out.write("\t\t$(\"#fm\").form(\"submit\",{\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tonSubmit:function(){\r\n");
      out.write("\t\t\t\t//所有数据填充完毕，最后再一次验证表单\r\n");
      out.write("\t\t\t\treturn $(this).form(\"validate\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t//alert(result);\r\n");
      out.write("\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"分配成功！\");\r\n");
      out.write("\t\t\t\t\t//重置属性值\r\n");
      out.write("\t\t\t\t\tresetValue();\r\n");
      out.write("\t\t\t\t\t//关闭对话框\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t//刷新表格数据\r\n");
      out.write("\t\t\t\t\t$(\"#dg\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"分配失败！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//关闭\r\n");
      out.write("\tfunction closeCustomerServiceDialog(){\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\tresetValue();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//重置属性值\r\n");
      out.write("\tfunction resetValue(){\r\n");
      out.write("\t\t$(\"#assigner\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"dg\" title=\"客户服务分配\" class=\"easyui-datagrid\" fitColumns=\"true\" pagination=\"true\" rownumbers=\"true\"\r\n");
      out.write("\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/customerService/list.do?state=新创建\" fit=\"true\" toolbar=\"#tb\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"cb\" checkbox=\"true\" align=\"center\"></th>\r\n");
      out.write("\t\t\t\t<th field=\"id\" width=\"50px\" align=\"center\">编号</th>\r\n");
      out.write("\t\t\t\t<th field=\"customer\" width=\"100px\" align=\"center\">客户</th>\r\n");
      out.write("\t\t\t\t<th field=\"overview\" width=\"200px\" align=\"center\">概要</th>\r\n");
      out.write("\t\t\t\t<th field=\"serveType\" width=\"100px\" align=\"center\">服务类型</th>\r\n");
      out.write("\t\t\t\t<th field=\"createPeople\" width=\"80px\" align=\"center\">创建人</th>\r\n");
      out.write("\t\t\t\t<th field=\"createTime\" width=\"100px\" align=\"center\">创建时间</th>\r\n");
      out.write("\t\t\t\t<th field=\"state\" width=\"50px\" align=\"center\" hidden=\"true\">客户服务状态</th>\r\n");
      out.write("\t\t\t\t<th field=\"assigner\" width=\"50px\" align=\"center\" hidden=\"true\">分配人</th>\r\n");
      out.write("\t\t\t\t<th field=\"assignTime\" width=\"50px\" align=\"center\" hidden=\"true\">分配日期</th>\r\n");
      out.write("\t\t\t\t<th field=\"serviceProce\" width=\"50px\" align=\"center\" hidden=\"true\">服务处理</th>\r\n");
      out.write("\t\t\t\t<th field=\"serviceProcePeople\" width=\"50px\" align=\"center\" hidden=\"true\">服务处理人</th>\r\n");
      out.write("\t\t\t\t<th field=\"serviceProceTime\" width=\"50px\" align=\"center\" hidden=\"true\">服务处理日期</th>\r\n");
      out.write("\t\t\t\t<th field=\"serviceProceResult\" width=\"50px\" align=\"center\" hidden=\"true\">服务处理结果</th>\r\n");
      out.write("\t\t\t\t<th field=\"myd\" width=\"50px\" align=\"center\" hidden=\"true\">客户满意度</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"tb\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a href=\"javascript:openCustomerServiceAssignDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-fwfp\" plain=\"true\">分配</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:620px;height:450px;padding:10px 20px\" closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"8px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>服务类型：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"serveType\" name=\"serveType\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>客户：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"customer\" name=\"customer\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>概要：</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><input type=\"text\" style=\"width:420px;\" id=\"overview\" name=\"overview\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>服务请求：</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><textarea rows=\"5\" cols=\"49\" id=\"servicerequest\" name=\"servicerequest\" readonly=\"readonly\"/></textarea></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>创建人：</td>\r\n");
      out.write("\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"state\" name=\"state\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"createPeople\" name=\"createPeople\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>创建时间：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"createTime\" name=\"createTime\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>分配给：</td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"easyui-combobox\" id=\"cusManager\"\r\n");
      out.write("\t\t\t\t\t\tname=\"cusManager\" panelHeight=\"auto\" editable=\"false\"\r\n");
      out.write("\t\t\t\t\t\tValueField=\"trueName\" textField=\"trueName\"\r\n");
      out.write("\t\t\t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/customerManagerCombolist.do\" />&nbsp;<font\r\n");
      out.write("\t\t\t\t\t\tcolor=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>分配时间：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"assignTime\" name=\"assignTime\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:saveCustomerService()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" plain=\"true\">保存</a>\r\n");
      out.write("\t\t<a href=\"javascript:closeCustomerServiceDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" plain=\"true\">关闭</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
