/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2020-04-12 12:09:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar url;\t\t//全局变量；每个函数都会用；链接地址\r\n");
      out.write("\t\r\n");
      out.write("\t//搜索\r\n");
      out.write("\tfunction searchUser(){\r\n");
      out.write("\t\t$(\"#dg\").datagrid(\"load\",{\r\n");
      out.write("\t\t\t\"userName\":$(\"#s_userName\").val()\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//打开用户对话框(添加)\r\n");
      out.write("\tfunction openUserAddDialog(){\r\n");
      out.write("\t\tresetValue();\t\t//打开添加界面时清空文本框内容\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"添加用户信息\");\r\n");
      out.write("\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/save.do\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//打开用户对话框(修改)\r\n");
      out.write("\tfunction openUserModifyDialog(){\r\n");
      out.write("\t\t//获取选中的行（可以选中多行，但只能修改一行）\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t//判断用户是否选择一行，如若不是则提示\r\n");
      out.write("\t\tif(selectRows.length != 1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要编辑的数据\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = selectRows[0];\t\t//当前记录的所有属性值\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"修改用户信息\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#fm\").form(\"load\",row);\r\n");
      out.write("\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/save.do?id=\"+row.id;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//保存\r\n");
      out.write("\tfunction saveUser(){\r\n");
      out.write("\t\t$(\"#fm\").form(\"submit\",{\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tonSubmit:function(){\r\n");
      out.write("\t\t\t\t//判断下拉框是否选中\r\n");
      out.write("\t\t\t\tif($(\"#roleName\").combobox(\"getValue\")==\"\"){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"请选择用户角色\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//所有数据填充完毕，进行最后一次调整\r\n");
      out.write("\t\t\t\treturn $(this).form(\"validate\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"保存成功！\");\r\n");
      out.write("\t\t\t\t\t//重置属性值\r\n");
      out.write("\t\t\t\t\tresetValue();\r\n");
      out.write("\t\t\t\t\t//关闭对话框\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t//刷新表格数据\r\n");
      out.write("\t\t\t\t\t$(\"#dg\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"保存失败！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//删除\r\n");
      out.write("\tfunction deleteUser(){\r\n");
      out.write("\t\t//获取用户选中的行（可以选中多行）\r\n");
      out.write("\t\tvar selectRows = $(\"#dg\").datagrid(\"getSelections\");\r\n");
      out.write("\t\t//判断用户是否选中记录\r\n");
      out.write("\t\tif(selectRows.length == 0){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择要删除的数据！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//储存用户选中的Id\r\n");
      out.write("\t\tvar strIds = [];\r\n");
      out.write("\t\tfor(var i=0;i < selectRows.length; i++){\r\n");
      out.write("\t\t\t//把选中的Id存到strIds数组里面\r\n");
      out.write("\t\t\tstrIds.push(selectRows[i].id)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//将数组变成字符串，按指定的符号隔开[11,12]\r\n");
      out.write("\t\tvar ids = strIds.join(\",\");\r\n");
      out.write("\t\t$.messager.confirm(\"系统提示\",\"您确定要删除这<font color='red' size='3'>\"+selectRows.length+\"</font>条记录吗？\",function(r){\r\n");
      out.write("\t\t\tif(r){\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/delete.do\",{ids:ids},function(result){\r\n");
      out.write("\t\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"系统提示\",\"数据删除成功！\");\r\n");
      out.write("\t\t\t\t\t\t//删除表格数据\r\n");
      out.write("\t\t\t\t\t\t$(\"#dg\").datagarid(\"reload\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"系统提示\",\"数据删除失败！\")\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//关闭\r\n");
      out.write("\tfunction closeUserDialog(){\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\tresetValue();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//重置属性值\r\n");
      out.write("\tfunction resetValue(){\r\n");
      out.write("\t\t$(\"#userName\").val(\"\");\r\n");
      out.write("\t\t$(\"#password\").val(\"\");\r\n");
      out.write("\t\t$(\"#trueName\").val(\"\");\r\n");
      out.write("\t\t$(\"#email\").val(\"\");\r\n");
      out.write("\t\t$(\"#phone\").val(\"\");\r\n");
      out.write("\t\t$(\"#roleName\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<table id=\"dg\" title=\"用户管理\" class=\"easyui-datagrid\" fitColumns=\"true\" pagination=\"true\" rownumbers=\"true\"\r\n");
      out.write("\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/list.do\" fit=\"true\" toolbar=\"#tb\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"cb\" checkbox=\"true\" align=\"center\"></th>\r\n");
      out.write("\t\t\t\t<th field=\"id\" width=\"50px\" align=\"center\">编号</th>\r\n");
      out.write("\t\t\t\t<th field=\"userName\" width=\"50px\" align=\"center\">用户名</th>\r\n");
      out.write("\t\t\t\t<th field=\"password\" width=\"50px\" align=\"center\">密码</th>\r\n");
      out.write("\t\t\t\t<th field=\"trueName\" width=\"50px\" align=\"center\">真实姓名</th>\r\n");
      out.write("\t\t\t\t<th field=\"email\" width=\"50px\" align=\"center\">邮箱</th>\r\n");
      out.write("\t\t\t\t<th field=\"phone\" width=\"50px\" align=\"center\">电话</th>\r\n");
      out.write("\t\t\t\t<th field=\"roleName\" width=\"50px\" align=\"center\">角色名</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead> \r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"tb\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a href=\"javascript:openUserAddDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">添加</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:openUserModifyDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">修改</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:deleteUser()\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">删除</a>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t客户姓名：<input type=\"text\" id=\"s_userName\" size=\"20\" onkeydown=\"if(event.keyCode==13) searchUser()\"/>\r\n");
      out.write("\t\t\t<a href=\"javascript:searchUser()\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">搜索</a>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:620px;height:250px;padding:10px 20px\" closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"8px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>用户名：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"userName\" name=\"userName\" class=\"easyui-validatebox\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>密码：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"password\" name=\"password\" class=\"easyui-validatebox\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>真实姓名：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"trueName\" name=\"trueName\" class=\"easyui-validatebox\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>邮箱：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"email\" name=\"email\" class=\"easyui-validatebox\" validType=\"email\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>电话：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"phone\" name=\"phone\" class=\"easyui-validatebox\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>用户角色：</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" id=\"roleName\" name=\"roleName\" style=\"width:154px\" editable=\"false\" panelHeight=\"auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择角色...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"系统管理员\">系统管理员</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"销售主管\">销售主管</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"客户经理\">客户经理</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"高管\">高管</option>\r\n");
      out.write("\t\t\t\t\t\t</select>&nbsp;<font color=\"red\">*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:saveUser()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">保存</a>\r\n");
      out.write("\t\t<a href=\"javascript:closeUserDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">关闭</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
