/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2019-09-06 08:32:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction openTab(text,url,iconCls) {\r\n");
      out.write("\t\tif($(\"#tabs\").tabs(\"exists\",text)){\r\n");
      out.write("\t\t\t$(\"#tabs\").tabs(\"select\",text);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar content = \"<iframe frameboder=0 scrolling='auto' style='width:100%;height:100%' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/page/\"+url+\"'></iframe>\"\r\n");
      out.write("\t\t\t$(\"#tabs\").tabs(\"add\",{\r\n");
      out.write("\t\t\t\ttitle:text,\r\n");
      out.write("\t\t\t\ticonCls:iconCls,\r\n");
      out.write("\t\t\t\tclosable:true,\r\n");
      out.write("\t\t\t\tcontent:content\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar url;\r\n");
      out.write("\t//打开密码对话框\r\n");
      out.write("\tfunction openPasswordModifyDialog(){\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"修改密码\");\r\n");
      out.write("\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/modifyPassword.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//修改密码\r\n");
      out.write("\tfunction modifyPassword(){\r\n");
      out.write("\t\t$(\"#fm\").form(\"submit\",{\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tonSubmit:function(){\r\n");
      out.write("\t\t\t\tvar oldPassword= $(\"#oldPassword\").val();\r\n");
      out.write("\t\t\t\tvar newPassword= $(\"#newPassword\").val();\r\n");
      out.write("\t\t\t\tvar newPassword2= $(\"#newPassword2\").val();\r\n");
      out.write("\t\t\t\tif(!$(this).form(\"validate\")){\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(oldPassword !='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"用户原密码输入错误！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(newPassword =='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"原密码和新密码不能一致！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(newPassword != newPassword2 ){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"两次密码输入不一致，请重新输入！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t return true;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tvar result = eval('('+result+')');\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"密码修改成功下次登录生效！\");\r\n");
      out.write("\t\t\t\t\t//重置属性值\r\n");
      out.write("\t\t\t\t\tresetValue();\r\n");
      out.write("\t\t\t\t\t//关闭对话框\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"密码修改失败！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closemodifyPasswordDialog(){\r\n");
      out.write("\t\tresetValue();\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction resetValue(){\r\n");
      out.write("\t\t$(\"#oldPassword\").val(\"\");\r\n");
      out.write("\t\t$(\"#newPassword\").val(\"\");\r\n");
      out.write("\t\t$(\"#newPassword2\").val(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logout(){\r\n");
      out.write("\t\t$.messager.confirm(\"系统提示\",\"你确定要退出系统?\",function(r){\r\n");
      out.write("\t\t\tif(r){\r\n");
      out.write("\t\t\t\t window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/logout.do\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"north\" style=\"height:78px;background-color:white\">\r\n");
      out.write("\t\t<table style=\"padding:5px\" width=\"100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/bglogo.png\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"50%\" align=\"right\" valign=\"bottom\">\r\n");
      out.write("\t\t\t\t\t<font size=\"3\">&nbsp;&nbsp;<strong>欢迎：</strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>【");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.trueName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('】');
      out.write('【');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.roleName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("】\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div region=\"west\" style=\"width:200px\" title=\"导航菜单\" split=\"true\">\r\n");
      out.write("\t\t<div class=\"easyui-accordion\" data-options=\"fit:true,border:false\">\r\n");
      out.write("\t\t\t<div title=\"营销管理\" data-options=\"selected:true,iconCls:'icon-yxgl'\" style=\"padding:10px\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('营销机会管理','saleChanceManage.jsp','icon-yxjhgl')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-yxjhgl'\" style=\"width:150px\">营销机会管理</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户开发计划','cusdevplanManage.jsp','icon-khkfjh')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khkfjh'\" style=\"width:150px\">客户开发计划</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"客户管理\"  data-options=\"iconCls:'icon-khgl'\" style=\"padding:10px;\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户信息管理','customerManage.jsp','icon-khxxgl')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khxxgl'\" style=\"width: 150px;\">客户信息管理</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户流失管理','customerLossManage.jsp','icon-khlsgl')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khlsgl'\" style=\"width: 150px;\">客户流失管理</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"服务管理\" data-options=\"iconCls:'icon-fwgl'\" style=\"padding:10px\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('服务创建','customerServiceCreate.jsp','icon-fwcj')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-fwcj'\" style=\"width: 150px;\">服务创建</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('服务分配','customerServiceAssign.jsp','icon-fwfp')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-fwfp'\" style=\"width: 150px;\">服务分配</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('服务处理','customerServiceProce.jsp','icon-fwcl')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-fwcl'\" style=\"width: 150px;\">服务处理</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('服务反馈','customerServiceFeedback.jsp','icon-fwfk')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-fwfk'\" style=\"width: 150px;\">服务反馈</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('服务归档','customerServiceFile.jsp','icon-fwgd')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-fwgd'\" style=\"width: 150px;\">服务归档</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"统计报表\"  data-options=\"iconCls:'icon-tjbb'\" style=\"padding:10px\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户贡献分析','khgxfx.jsp','icon-khgxfx')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khgxfx'\" style=\"width: 150px;\">客户贡献分析</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户构成分析','khgcfx.jsp','icon-khgcfx')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khgcfx'\" style=\"width: 150px;\">客户构成分析</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户服务分析','khfwfx.jsp','icon-khfwfx')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khfwfx'\" style=\"width: 150px;\">客户服务分析</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('客户流失分析','khlsfx.jsp','icon-khlsfx')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-khlsfx'\" style=\"width: 150px;\">客户流失分析</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"基础数据管理\"  data-options=\"iconCls:'icon-jcsjgl'\" style=\"padding:10px\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('数据字典管理','dataDicManage.jsp','icon-sjzdgl')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-sjzdgl'\" style=\"width: 150px;\">数据字典管理</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('产品信息查询','productSearch.jsp','icon-cpxxgl')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-cpxxgl'\" style=\"width: 150px;\">产品信息查询</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openTab('用户信息管理','userManage.jsp','icon-user')\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-user'\" style=\"width: 150px;\">用户信息管理</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"系统管理\"  data-options=\"iconCls:'icon-item'\" style=\"padding:10px\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:openPasswordModifyDialog()\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-modifyPassword'\" style=\"width: 150px;\">修改密码</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:logout()\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-exit'\" style=\"width: 150px;\">安全退出</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div region=\"center\">\r\n");
      out.write("\t\t<div class=\"easyui-tabs\" fit=\"true\" border=\"false\" id=\"tabs\">\r\n");
      out.write("\t\t\t<div title=\"首页\" data-options=\"iconCls:'icon-home'\">\r\n");
      out.write("\t\t\t\t<div align=\"center\" style=\"padding-top:100px\"><font color=\"red\" size=\"10\">欢迎使用</font></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:320px;height:250px;padding:10px 20px\" closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t\t<table cellspacing=\"8px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>用户名：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"userName\" name=\"userName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly=\"readonly\" ></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>原密码：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"oldPassword\" name=\"oldPassword\" class=\"easyui-validatebox\"  required=\"true\" >&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>新密码：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"newPassword\" name=\"newPassword\" class=\"easyui-validatebox\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>确认新密码：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"newPassword2\" name=\"newPassword2\" class=\"easyui-validatebox\" required=\"true\">&nbsp;<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:modifyPassword()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">保存</a>\r\n");
      out.write("\t\t<a href=\"javascript:closemodifyPasswordDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">关闭</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
